version: '3'

services:
  puller:
    image: melca/puller:1.0 
    container_name: puller
    volumes:
      - ./data:/data
    restart: always
    user: root

  web:
    image: melca/nginx:1.25.3-alpine
    container_name: web
    ports:
      - 80:80
    volumes:
      - ./data:/data 
    restart: always
    user: root
